#server:
#  port: 9999
#  
#spring:
#  application:
#    name: bus-demo
#    
#  cloud:
#    stream:
#      binders:
#        rabbit1:
#          type: rabbit
#          environment:
#            spring:
#              rabbitmq:
#                host: xxx
#                port: 5672
#                username: admin
#                password: admin
#                publisher-confirms: true
#      bindings:
#        springCloudBusInput:
#          binder: rabbit1
#        springCloudBusOutput:
#          binder: rabbit1
#    bus:
#      destination: bus-queue
#      trace:
#        enabled: true
#          
#                
